### ISSUE TITLE
assumes the precision of each price feed

### ISSUE THREAD

**Issue by Kim8584** [Cyfrin/foundry-defi-stablecoin-f23#10] opened 2023-06-11 07:39 UTC

**Comment by Kim8584** [comment] 2023-06-11 07:48
the contract is build to support many token contracts but only accounts for the precision of ETH/USD which is 8  and so getUsdValue() will give an errored value when other  pricefeeds are use( in the event that the contract is deployed with another token)

**Comment by Amtaf** [comment] 2023-07-31 12:17
I have been following the video, I got to the point where I'm doing unit tests for getUsdvalue() but I'm getting "EvmError: Revert " could this be caused by the Additional_Feed_Precision?

**Comment by EngrPips** [comment] 2023-07-31 12:30
> I have been following the video, I got to the point where I'm doing unit tests for getUsdvalue() but I'm getting "EvmError: Revert " could this be caused by the Additional_Feed_Precision?

I would suggest you provide more information so people can help you debug the error , just saying you got “EvmErro: Revert” won’t really help. Send the details of the error and probably your text code for that particular test giving that error

**Comment by usmanfarooq91** [comment] 2023-07-31 12:30
It would be better to ask this question [here](https://github.com/Cyfrin/foundry-full-course-f23/discussions) and if possible share your project's GitHub repo, or specific code snippets related to this problem. i.e. definition of `getUsdvalue()` function, also your test file etc.

**Comment by Amtaf** [comment] 2023-07-31 14:01
> It would be better to ask this question [here](https://github.com/Cyfrin/foundry-full-course-f23/discussions) and if possible share your project's GitHub repo, or specific code snippets related to this problem. i.e. definition of `getUsdvalue()` function, also your test file etc.

Thank you @usmanfarooq91 @EngrPips I have posted it in [discusions](https://github.com/Cyfrin/foundry-full-course-f23/discussions/498)

**Comment by harpreettrader** [comment] 2023-08-01 00:56
> I have been following the video, I got to the point where I'm doing unit tests for getUsdvalue() but I'm getting "EvmError: Revert " could this be caused by the Additional_Feed_Precision?

buddy could you pls provide more information regarding the error that are getting so that we can help you

**Comment by PatrickAlphaC** [comment] 2023-08-01 02:16
Closing this issue, please continue in the discussions.

**Closed by PatrickAlphaC** 2023-08-01 02:16 UTC
